### ISSUE TITLE
您好，请问“抓包得到的post数据”是什么，应该如何获取，感谢

### ISSUE THREAD

**Issue by zysyz0** [Lyrance/upload_everyday#4]
如题

**Comment by Lyrance** [comment]
抓到的包的表单主体
ios用stream
安卓用小黄鸟
具体怎么使用可以百度

**Comment by zysyz0** [comment]
> 抓到的包的表单主体 ios用stream 安卓用小黄鸟 具体怎么使用可以百度

抓包所得到的post是永久的吗，还是间隔多久要再更新一次

**Comment by Lyrance** [comment]
qdu是以信息采集方式进行的上报，只要他的填写问题不变就不用改
