### ISSUE TITLE
小程序了，还有救嘛

### ISSUE THREAD

**Issue by bybl6966** [Lyrance/upload_everyday#5]
如题

**Comment by Lyrance** [comment]
给你一个思路，他提交的方式没变但是登录方式变了，你自己去看看他怎么登陆的，因为涉及到微信所以没法公开了，只能自己用了

**Comment by bybl6966** [comment]
> 给你一个思路，他提交的方式没变但是登录方式变了，你自己去看看他怎么登陆的，因为涉及到微信所以没法公开了，只能自己用了

抓包看过了，获取cookies那里有个GET请求（一打开小程序），参数code没法得到

**Comment by Lyrance** [comment]
学习一下ssid
