### ISSUE TITLE
大佬我又来了，关于小程序填报

### ISSUE THREAD

**Issue by bybl6966** [Lyrance/upload_everyday#7]
对登录操作进行了抓包，发现最开始使用的code是通过wx.login方法实现的，目前好像没有可能得到小程序的密钥生成对应的code
并且实现具体功能用到的current和ssid失效时间较快，且只能通过code获取token后得到
请大佬点拨！

**Comment by Lyrance** [comment]
你再看看抓的包里有个keepalive

**Comment by bybl6966** [comment]
> 你再看看抓的包里有个keepalive

确实看到每隔几秒会有发包保持ssid有效，不知道学长是不是说的这个。但这样存在登录冲突问题：一旦在重新打开小程序先前ssid就会失效
在需要打开小程序的情况下还是无法实现长时间使用
